### ISSUE TITLE
Resources Page nav

### ISSUE THREAD

**Issue by hankache** [Raku/raku.org#90] opened 2018-01-14 18:06 UTC
The books section is way bigger than the others.
![resources](https://user-images.githubusercontent.com/15119547/34919023-efe99002-f965-11e7-91b1-63c1b20cc441.jpg)

**Comment by zoffixznet** [comment] 2018-01-14 20:03
That's by design. It has more content than the others...

**Comment by coke** [comment] 2023-10-05 03:23
Agree with @zoffixznet , closing ticket. Thanks for the report.

**Closed by coke** 2023-10-05 03:23 UTC
