### ISSUE TITLE
execute examples on glot.io

### ISSUE THREAD

**Issue by ufobat** [Raku/raku.org#99] opened 2018-03-23 16:49 UTC
It would be a nice feature if you could edit and execute the code of the examples on https://examples.perl6.org. 

https://irclog.perlgeek.de/perl6/2018-03-23#i_15957524

Similar to the Rustbook (e.g. https://doc.rust-lang.org/book/second-edition/ch03-04-comments.html) or posts on https://rakudo.party/post/Perl-6-Seqs-Drugs-and-Rock-n-Roll

**Comment by JJ** [comment] 2018-03-23 16:55
That would be nice. I'm not sure about all the examples, however...

**Comment by zoffixznet** [comment] 2018-03-26 00:44
FWIW, upcoming perl6.org update will include swapping to a dynamic app that will have glot.io API to run the examples on our home page. The examples.perl6.org site is not included in that update, but it's possible the in-webpage code runner could be added with a bit of JS to those sites, using perl6.org's backend.

**Comment by AlexDaniel** [comment] 2018-03-26 00:57
@zoffixznet sounds awesome! Thanks!

**Comment by coke** [comment] 2023-10-05 03:07
Closing as duplicate of #81

**Closed by coke** 2023-10-05 03:07 UTC
Labels: BS4
